openapi: 3.0.0
info:
  title: Kiwi Promotional Codes
  version: '1.0'
  description: 'Retrieve a list of kiwi.com promotional codes along with important additional information. Additional information can include the booking ID, the reason for the promotional code’s creation, if the promotional code has been used, the amount (in euro) that the promotional code covers, as well as the email account details of promotional code users. **Note**: The Kiwi Promocodes API is only accessible (via https) to authorized users. **Note**: This API connects directly to the kiwi.com backend; consequently, the Kiwi team recommends that you only use this API to interact with our promotional codes.               '
  contact:
    name: Kiwi Support
    url: 'https://kiwi.com/api'
    email: email@kiwi.com
  termsOfService: 'https://kiwi.com/terms'
  license:
    name: Apache 2.0
    url: 'https://kiwi.com/price'
servers:
  - url: 'http://promocodes.kiwi.com'
    description: Promocodes
paths:
  /promocodes:
    get:
      summary: Your GET endpoint
      tags:
        - promocodes endpoints
      operationId: get-promocodes
      description: "Access a list of kiwi.com promocodes along with additional information like the booking's ID, the reaons behind the promocode's creation, promocode use, the amount (€) the promocode covers, as well as the email account details of promocode users.    "
      parameters:
        - schema:
            type: string
          in: query
          name: code
          description: '**Code**. Search by unique alphnumeric code. *Example: AAAAR*. '
          required: true
        - schema:
            type: integer
          in: query
          name: BID
          description: "**BID**. Calls the booking ID (*Example: 203589*) and reasons for the promocode's creation.  "
        - schema:
            type: boolean
          in: query
          name: used
          description: '**Used**. If *true*, the promocode has been used.'
        - schema:
            type: integer
          in: query
          name: amount
          description: '**Amount**. Calls the monetary amount in euro that the promocode covers. *Example: 450.00*   '
        - schema:
            type: string
          in: query
          name: email
          description: '**Email**. Calls the email details of promocode users. *Example: joansmyth@email.com*.  '
      security:
        - app_id: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: AAAAQ
                    description: "The promocode's unique alphanumeric code"
                  bid:
                    type: integer
                    example: 'null'
                    description: The booking ID
                  used:
                    type: boolean
                    example: 'false'
                    description: "The status of promocode's use"
                  amount:
                    type: integer
                    example: 152
                    description: 'The amount in euro the promcode covers '
                  email:
                    type: string
                    example: joansmyth@email.co
                    description: Email details of promocode users
                required:
                  - code
              examples:
                Schema Example:
                  value:
                    promocodes:
                      - code: AAAAQ
                        bid: null
                        used: false
                        amount: 152
                        email: joansmythh@email.com
components:
  schemas: {}
  securitySchemes:
    app_id:
      type: http
      scheme: oauth
      description: Access is available to authorized users via http.
